# Generated by Django 3.2.13 on 2022-05-21 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=45)),
                ('sub_subject', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('brand', models.IntegerField()),
                ('writer', models.CharField(max_length=50, null=True)),
                ('price', models.IntegerField()),
                ('pageCnt', models.IntegerField()),
                ('questionCnt', models.IntegerField()),
                ('viewCnt', models.IntegerField(default=0)),
                ('reviewCnt', models.IntegerField(default=0)),
                ('questionType', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=None, null=True)),
                ('tagSame', models.TextField(default=None, null=True)),
                ('tagSubject', models.TextField(default=None, null=True)),
                ('subjectIdx', models.ForeignKey(db_column='subjectIdx', on_delete=django.db.models.deletion.CASCADE, to='search.subject')),
                ('userIdx', models.ForeignKey(db_column='userIdx', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
