# Generated by Django 4.0.4 on 2022-05-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tagSame',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='tagSubject',
            field=models.TextField(null=True),
        ),
    ]
