# Generated by Django 4.0.4 on 2022-05-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_book_tagsame_alter_book_tagsubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tagSame',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='tagSubject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
