# Generated by Django 3.2.13 on 2022-05-21 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korGrade', models.IntegerField()),
                ('mathGrade', models.IntegerField()),
                ('engGrade', models.IntegerField()),
                ('s1Grade', models.IntegerField()),
                ('s2Grade', models.IntegerField()),
                ('hisGrade', models.IntegerField()),
                ('userIdx', models.ForeignKey(db_column='userIdx', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=10)),
                ('userStatus', models.CharField(choices=[('고등학생', '고등학생'), ('n수생', 'n수생'), ('대학생', '대학생'), ('과외선생님', '과외선생님'), ('학원 아르바이트', '학원 아르바이트'), ('무직', '무직'), ('기타', '기타')], max_length=10)),
                ('address', models.TextField()),
                ('reviewPoint', models.IntegerField(default=0)),
                ('gender', models.IntegerField()),
                ('phoneNum', models.IntegerField()),
                ('gradeIdx', models.ForeignKey(db_column='gradeIdx', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.grade')),
                ('userIdx', models.ForeignKey(db_column='userIdx', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
