# Generated by Django 3.2.13 on 2022-05-21 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
                ('subject', models.ForeignKey(db_column='subject', on_delete=django.db.models.deletion.CASCADE, to='search.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('content', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='review')),
                ('tagSame', models.TextField()),
                ('tagSub', models.TextField()),
                ('bookIdx', models.ForeignKey(db_column='bookIdx', on_delete=django.db.models.deletion.CASCADE, to='search.book')),
                ('userIdx', models.ForeignKey(db_column='userIdx', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
