# Generated by Django 4.0.4 on 2022-05-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='tagSame',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='tagSub',
            field=models.TextField(),
        ),
    ]
